import { AuthProvider } from "@/components/auth-provider";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/shared/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <Navbar />
          <main>{children}</main>
        </body>
      </AuthProvider>
    </html>
  );
}
